export const contractSelectFields = {
    id: true,
    clientId: true,
    startDate: true,
    endDate: true,
    renewalDate: true,
    billingRate: true,
    isRenewable: true,
    isAutoRenew: true,
    paymentStatus: true,
    paymentFrequency: true,
    paymentTerms: true,
    currency: true,
    lastBillingDate: true,
    nextBillingDate: true,
    documentUrl: true,
    status: true,
    signedBy: true,
    signedAt: true,
    terminationReason: true,
    notes: true,
    createdAt: true,
    updatedAt: true,
    client: {
        select: {
            id: true,
            name: true,
        },
    },
} as const;
