// types/enums.ts
export enum Gender { MALE = "MALE", FEMALE = "FEMALE", OTHER = "OTHER" }
export enum IdType { PASSPORT = "PASSPORT", NATIONAL_ID = "NATIONAL_ID", DRIVING_LICENSE = "DRIVING_LICENSE", OTHER = "OTHER" }
export enum Language { ENGLISH = "ENGLISH", SPANISH = "SPANISH", FRENCH = "FRENCH", GERMAN = "GERMAN", OTHER = "OTHER" }
export enum ContactMethod { EMAIL = "EMAIL", PHONE = "PHONE", SMS = "SMS", WHATSAPP = "WHATSAPP", OTHER = "OTHER" }
export enum ManagementLevel { JUNIOR = "JUNIOR", MID = "MID", SENIOR = "SENIOR", EXECUTIVE = "EXECUTIVE", OTHER = "OTHER" }
export enum MaritalStatus { SINGLE = "SINGLE", MARRIED = "MARRIED", DIVORCED = "DIVORCED", WIDOWED = "WIDOWED" }
export enum WorkStatus { ACTIVE = "ACTIVE", INACTIVE = "INACTIVE", ON_LEAVE = "ON_LEAVE", TERMINATED = "TERMINATED" }
export enum EmploymentType { FULL_TIME = "FULL_TIME", PART_TIME = "PART_TIME", CONTRACT = "CONTRACT", TEMPORARY = "TEMPORARY", CONSULTANT = "CONSULTANT" }
export enum EducationLevel { HIGH_SCHOOL = "HIGH_SCHOOL", DIPLOMA = "DIPLOMA", BACHELORS = "BACHELORS", MASTERS = "MASTERS", PHD = "PHD" }
